apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: namespace-only
  name: ns-app-sub
  namespace: default
spec:
  channel: default/gitops
  placement:
    placementRef:
      kind: Placement
      name: placement
      namespace: default
